spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Microservicio de seguridad
        - id: Security
          uri: http://localhost:9191
          predicates:
            - Path=/api/auth/login
            - Path=/api/auth/register
            - Path=/api/roles # Para roles

        # Microservicio de calificaciones
        - id: Bryan
          uri: http://localhost:8383
          predicates:
            - Path=/api/calificaciones/**
            - Path=/api/calificaciones-detalle/**
            - Path=/api/categorias/**
            - Path=/api/tipos-de-precio/**
            - Path=/api/estados/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 7123c42a4aaa8520642e0f1d935d2699936ca753fb183d5bde11df82804d04d1

server:
  port: 7575

authentication:
  enabled: true
